import Header from "@/components/layout/dashboard/header/header";
import DefaultSidebar from "@/components/layout/dashboard/sidebar/sidebar";
import { getServerSideProps } from "@/components/pages/dashboard/home/action";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Tailwind with Hoailt",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await getServerSideProps();
  async function onLogOut() {
    "use server";
    cookies().delete("role");
    redirect("/sign-in");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gradient bg-no-repeat bg-center bg-cover min-h-[100vh]">
          {cookieStore.props.posts === true ? (
            <>
              <Header onLogOut={onLogOut} />
              <DefaultSidebar childrend={children} />
            </>
          ) : (
            redirect("/sign-in")
          )}
        </main>
      </body>
    </html>
  );
}
